language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
install:
  - yarn install
script:

deploy:
  - provider: npm
    email: zhang_renyang@126.com  
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      branch: master
  
  